### ISSUE TITLE
連寫的 輕聲詞若是出現佇句頭，會錯誤

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/khin1siann1-hun1sik4#8]
https://travis-ci.org/i3thuan5/su5lui3-hun1kip4-hok8bu7/jobs/393962020

可能是因為教典內底有`--了-了`
```
======================================================================
ERROR: test_教典連結 (試驗.統計.test教典連結.教典連結試驗)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/i3thuan5/su5lui3-hun1kip4-hok8bu7/試驗/統計/test教典連結.py", line 18, in test_教典連結
    結果 = _算詞頻csv()
  File "/home/travis/build/i3thuan5/su5lui3-hun1kip4-hok8bu7/拍字/介面/統計.py", line 84, in _算詞頻csv
    教典詞目 = 教典物件.揣詞條()
  File "/home/travis/build/i3thuan5/su5lui3-hun1kip4-hok8bu7/拍字/教典.py", line 19, in 揣詞條
    self._產生詞條()
  File "/home/travis/build/i3thuan5/su5lui3-hun1kip4-hok8bu7/拍字/教典.py", line 32, in _產生詞條
    全部詞結果 = self._讀取詞目(檔.read().decode())
  File "/home/travis/build/i3thuan5/su5lui3-hun1kip4-hok8bu7/拍字/教典.py", line 50, in _讀取詞目
    對齊句物件(漢字, 臺羅)
  File "/home/travis/build/i3thuan5/su5lui3-hun1kip4-hok8bu7/拍字/書寫斷詞.py", line 18, in 對齊句物件
    分析物件 = _輕聲分析器.輕聲分析(句物件)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/輕聲分析/分析.py", line 20, in 輕聲分析
    規句詞陣列 = self.連寫詞間輕聲(拆好詞陣列)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/輕聲分析/分析.py", line 136, in 連寫詞間輕聲
    新的詞陣列[-1] += 一詞字陣列
IndexError: list index out of range
```

**Comment by a8568730** [comment]
解決了
